services:
  server:
    container_name: pwn.5.Vault_of_Lost_Memories
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7007:1337"
    privileged: true
    env_file:
      - .env