version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
      
