version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          pids: 1000
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app