version: '3.8'
services:
  server:
    container_name: pwn.2.brave_heap
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7002:1337"
    privileged: true
    env_file:
      - .env
